### ISSUE TITLE
excess journal messages: Invalid argument (did you enable fan_control=1?)

### ISSUE THREAD

**Issue by cmurf** [cdown/zcfan#2]
I'm getting this line about once per second:
>Apr 07 10:59:10 fovo.local zcfan[14186]: /proc/acpi/ibm/fan: write: Invalid argument (did you enable fan_control=1?)

I have not done "Load your thinkpad_acpi module with fan_control=1". 

Also if the thinkpad_acpi module isn't loaded at all I also get this message about once per second:

>Apr 07 11:04:48 fovo.local zcfan[14186]: /proc/acpi/ibm/fan: fopen: No such file or directory

Once the user follows directions, and the module is loaded with the correct parameter, the excess messages go away. But maybe once a minute is enough? Or even once?

Using zcfan-1.1.0-1.fc36.x86_64, kernel-5.17.1-300.fc36.x86_64

**Comment by cdown** [comment]
Hi! Thanks for bringing this up. This is currently tied to how often we write to the fan, which (if we failed) is once per tick, with one tick a second.

There are a few options here:

1. Just quit on failure. This in theory works, but it may paper over other problems if systemd autorestart is enabled.
2. Artifically inject a delay after the failure. This could work, but we'd need to think about how it should work if there's a failure while the watchdog is enabled.
3. Just suppress the message.
4. Exit if the first run fails, but otherwise keep on going (and don't suppress the message).

Probably option 3 or 4 is my preferred solution, and 4 has the advantage that it's harder for the user to miss the fact that something is not working.

**Comment by cmurf** [comment]
Can systemd do a condition check for loaded kernel modules? I'm wondering if at some future point Fedora can install and enable the zcfan.service by default, and have it skipped/not started on non-thinkpads (i.e. thinkpad_acpi module isn't loaded).

**Comment by cdown** [comment]
It could check `ConditionPathExists=/sys/module/thinkpad_acpi`, but that wouldn't tell you if fan_control was enabled.

**Comment by cdown** [comment]
For the original problem, let me know what you think about 978af4c3d7d754fc886909de0b6742bd9750bc6a. :-)
