### ISSUE TITLE
can not install 

### ISSUE THREAD

**Issue by kristof-linux** [cdown/zcfan#24]
Hello,
Please can somebody help? If i try to install with make, i get error 

```
zcfan.c:1:10: fatal error: errno.h: Bestand of map bestaat niet
    1 | #include <errno.h>
      |          ^~~~~~~~~
```

Please can somebody help? I'm not so experienced in this kind of things. Thx!

![Schermafdruk van 2024-01-18 09-15-58](https://github.com/cdown/zcfan/assets/58733661/5fba4229-bced-411c-9fab-05e34faaf65c)

**Comment by errge** [comment]
When reporting build errors with screenshots, please try to make sure that the error messages are in English.  You can achieve this by using the command `LANG=C LC_MESSAGES=C make` instead of `make`.

Assuming that the error message is "no such file or directory" on `errno.h`, the problem is that your system doesn't have basic build dependencies installed for the compilation to succeed.  Assuming you are using Debian/Ubuntu, you can use the following commands to install basic build dependencies for any kind of build: `apt install build-essential`, and then you can use `apt build-dep zcfan` for zcfan specific dependencies.  Before all of this, you might have to do `apt update`, to make sure that your package listings are up-to-date.

The procedure is different for other distributions, so if you are not using a debian based distro, you will have to do your own research.

**Comment by cdown** [comment]
Hi! What @errge said is correct, you almost certainly want `build-essential`.

**Comment by kristof-linux** [comment]
Hello, thanks so much for your help. 
I tried to follow your advice but now i'm stuck on a new error "You must put some 'deb-src' URIs in your sources.list"
Please can you help me!!


![afbeelding](https://github.com/cdown/zcfan/assets/58733661/f9feb599-9bcf-4e59-a962-341122390eb2)
