### ISSUE TITLE
Fan level is lost after resume

### ISSUE THREAD

**Issue by sgf-dma** [cdown/zcfan#35]
Hi.

On T530 fan level is reset to 'auto' after resume. How long pc was in sleep  (i.e. longer, than watchdog timeout or not) does not seem to matter.

I think, this is regression after commit 0c3ac328, when you switch from writing current fan level in 'maybe_ping_watchdog' to writing watchdog timeout. Probably, the old code from 'time_jump' branch (69b0a4a) may be adapted to fix this issue. But there's still a question what to do, if sleep duration was shorter, than 3 sec. Maybe reread current fan level every, say.. hour?

And thanks for great software!

**Comment by cdown** [comment]
Thank you very much for the report and previous discussions! I had forgotten about some of those, so that was helpful.

I think 014d2e8847dc0fd232b330c6dfc9b53e9d514840 should help here. I don't have affected hardware, but at least the detection part works for me. Could you test it out and report back?

Thank you!

**Comment by cdown** [comment]
(016498f is the same, just fixing some bogus clang warning.)

**Comment by sgf-dma** [comment]
Tested the branch cdown/2024-12-16/suspend (4c1561c ) and it works fine. Thanks a lot!

**Comment by cdown** [comment]
Thanks for getting back!
